<a href="https://colab.research.google.com/github/theshashank1/cse-c5-3year-da/blob/main/numpy_cse_c5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
! pip install numpy

In [2]:
n = 1000000
python_list = list(range(n))

In [5]:
import numpy as np

In [6]:
numpy_array = np.arange(n)

In [10]:
import time

start = time.perf_counter()
result = [x + 5 for x in python_list]
end = time.perf_counter()
print(end - start)

0.033035008000069865


In [11]:
import time

start = time.perf_counter()
result = numpy_array + 5
end = time.perf_counter()
print(end - start)

0.011479999999892243


# Creating NumPy Arrays

In [12]:
import numpy

In [13]:
List = [1,2,3,4,5]
print(type(List))

<class 'list'>


In [14]:
numpy_array = numpy.array(List)

array([1, 2, 3, 4, 5])

In [15]:
print(type(numpy_array))

<class 'numpy.ndarray'>


In [18]:
array1 = numpy.array([1,2,3,4])

In [20]:
print(type(array1))

<class 'numpy.ndarray'>


In [21]:
array1.ndim

1

In [22]:
import numpy as np


In [23]:
array2 = np.array([[1,2,3], [4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
array2.ndim

2

In [28]:
array3 = np.array([[[1,2,2,4], [1,2,3,4]],
 [[1,2,3,4], [1,2,3,4]]])
array3

array([[[1, 2, 2, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [29]:
array3.ndim

3

In [34]:
array3.shape

(2, 2, 4)

In [35]:
array2.shape

(2, 3)

In [39]:
# Creating array using the zeros method
zeros = np.zeros((2,3))
zeros

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [42]:
# Creating array using ones method
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
# Creating array using arange method
arange = np.arange(5,10)
arange

array([5, 6, 7, 8, 9])

In [56]:
random = np.random.rand(5)
random

array([0.10673447, 0.95746218, 0.10733112, 0.89729098, 0.77886471])

In [58]:
np.empty((2,3))

array([[1.05528021e-315, 0.00000000e+000, 2.33419537e-312],
       [2.35541533e-312, 2.33419537e-312, 9.76118064e-313]])

In [60]:
np.full((1,5), 1)

array([[1, 1, 1, 1, 1]])

# Indexing or Refering the Elements

In [48]:
arange[1]

np.int64(6)

In [49]:
array3[0][0][3]

np.int64(4)

In [50]:
array2[1][1]

np.int64(5)

In [54]:
array3[1,1,1]

np.int64(2)

In [61]:
arange[-1]

np.int64(9)

In [62]:
array2[-1][-1]

np.int64(6)

# Numpy Attributes

In [63]:
arange.ndim

1

In [64]:
arange.size

5

In [65]:
arange.dtype

dtype('int64')

In [66]:
arange.data

In [67]:
arange.itemsize

8

# Slicing

In [71]:
arange[0:3:2]

array([5, 7])

In [73]:
arange[2:5]

array([7, 8, 9])

In [74]:
arange[:]

array([5, 6, 7, 8, 9])

In [77]:
arange[3:]


array([8, 9])

In [76]:
arange[3::2]

array([8])

In [81]:
# Modifyig elements in the array
arange[3:] = 20
arange

array([ 5,  6,  7, 20, 20])

# Reshaping

In [86]:
arange = np.arange(6)
arange

array([0, 1, 2, 3, 4, 5])

In [87]:
arange.shape

(6,)

In [92]:
np.reshape(arange, (1,2,3))

array([[[0, 1, 2],
        [3, 4, 5]]])

In [100]:
arange % 5

array([0, 1, 2, 3, 4, 0])

In [106]:
a = np.arange(5)
b = np.arange(4,9)

In [107]:
a

array([0, 1, 2, 3, 4])

In [108]:
b

array([4, 5, 6, 7, 8])

In [109]:
a + b

array([ 4,  6,  8, 10, 12])

In [110]:
np.add(a,b)

array([ 4,  6,  8, 10, 12])

In [111]:
a - b

array([-4, -4, -4, -4, -4])

In [112]:
np.subtract(a,b)

array([-4, -4, -4, -4, -4])

In [113]:
a * b

array([ 0,  5, 12, 21, 32])

In [114]:
np.multiply(a, b)

array([ 0,  5, 12, 21, 32])

In [115]:
a / b

array([0.        , 0.2       , 0.33333333, 0.42857143, 0.5       ])

In [116]:
np.divide(a,b)

array([0.        , 0.2       , 0.33333333, 0.42857143, 0.5       ])

In [117]:
a ** b

array([    0,     1,    64,  2187, 65536])

In [118]:
np.power(a, b)

array([    0,     1,    64,  2187, 65536])

In [119]:
a % b

array([0, 1, 2, 3, 4])

In [120]:
np.mod(a, b)

array([0, 1, 2, 3, 4])

In [121]:
a < b

array([ True,  True,  True,  True,  True])

In [122]:
a == b

array([False, False, False, False, False])

# Matrix Operations

In [124]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [125]:
b = np.array([[5,6], [6,7]])
b

array([[5, 6],
       [6, 7]])

In [128]:
a / b

array([[0.2       , 0.33333333],
       [0.5       , 0.57142857]])

In [129]:
np.dot(a,b)

array([[17, 20],
       [39, 46]])

In [131]:
np.transpose(b)

array([[5, 6],
       [6, 7]])

In [132]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [133]:
np.linalg.det(a)

np.float64(-2.0000000000000004)